#!/usr/bin/env python3
"""
Neuro-Symbolic Reasoner: LLM-Augmented Chemical Explanation Engine
===================================================================
Combines Graph Neural Network predictions with Large Language Model reasoning
to generate scientifically accurate, interpretable toxicity explanations.

Paper: DeNovo-XAI: Interpretable Molecular Toxicity Prediction through
       LLM-Augmented Graph Neural Networks

Architecture:
    GNN Attention → Substructure Mapping → LLM Reasoning → Scientific Report

Author: DeNovo-XAI Research Team
Version: 1.0.0
"""

import os
import json
import logging
from abc import ABC, abstractmethod
from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass, field, asdict
from datetime import datetime
from enum import Enum

# Configure logging for research reproducibility
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger('NeuroSymbolicReasoner')


class RiskLevel(Enum):
    """Toxicity risk classification levels."""
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MODERATE = "MODERATE"
    LOW = "LOW"
    MINIMAL = "MINIMAL"


@dataclass
class ToxicityEvidence:
    """
    Structured evidence supporting a toxicity prediction.
    Used for building interpretable explanations.
    """
    substructure_name: str
    smarts_pattern: str
    atom_indices: List[int]
    attention_score: float  # 0-1, from GNN
    toxicity_category: str
    mechanism: str
    confidence: float = 0.0


@dataclass
class MolecularContext:
    """
    Complete molecular context for LLM reasoning.
    Contains all information needed to generate explanations.
    """
    smiles: str
    canonical_smiles: str = ""
    molecular_formula: str = ""
    molecular_weight: float = 0.0
    num_atoms: int = 0
    num_heavy_atoms: int = 0
    num_rings: int = 0
    num_aromatic_rings: int = 0
    logp: float = 0.0
    tpsa: float = 0.0  # Topological Polar Surface Area


@dataclass 
class PredictionResult:
    """
    Complete prediction result with all endpoint scores.
    """
    overall_toxicity: float  # 0-1 probability
    endpoint_scores: Dict[str, float] = field(default_factory=dict)
    risk_level: RiskLevel = RiskLevel.MODERATE
    toxic_endpoints: List[str] = field(default_factory=list)
    safe_endpoints: List[str] = field(default_factory=list)


@dataclass
class ExplanationReport:
    """
    Complete explanation report generated by the reasoner.
    This is the final output for end users and paper figures.
    """
    # Input (required - no defaults)
    smiles: str
    timestamp: str
    
    # Optional with defaults
    model_version: str = "DeNovo-XAI v1.0"
    molecular_context: Optional[MolecularContext] = None
    
    # Predictions
    prediction: Optional[PredictionResult] = None
    
    # Evidence
    identified_toxicophores: List[ToxicityEvidence] = field(default_factory=list)
    critical_atoms: List[Dict] = field(default_factory=list)
    
    # LLM-generated explanations
    executive_summary: str = ""
    detailed_mechanism: str = ""
    similar_compounds: List[str] = field(default_factory=list)
    safety_recommendations: List[str] = field(default_factory=list)
    
    # Confidence metrics
    explanation_confidence: float = 0.0
    attention_coverage: float = 0.0  # How much attention is explained by known patterns
    
    def to_dict(self) -> Dict:
        """Convert to dictionary for JSON serialization."""
        return asdict(self)
    
    def to_json(self) -> str:
        """Convert to formatted JSON string."""
        return json.dumps(self.to_dict(), indent=2, default=str)


class PromptTemplate:
    """
    Scientifically-designed prompt templates for LLM reasoning.
    Each template is optimized for specific explanation tasks.
    """
    
    # ═══════════════════════════════════════════════════════════════════════
    # Executive Summary Prompt
    # ═══════════════════════════════════════════════════════════════════════
    EXECUTIVE_SUMMARY = """You are an expert toxicologist and medicinal chemist. Analyze the following molecular toxicity prediction and provide a concise executive summary.

## Molecule Information
- SMILES: {smiles}
- Molecular Weight: {molecular_weight:.2f} g/mol
- Predicted Toxicity Probability: {toxicity_probability:.1%}
- Risk Level: {risk_level}

## Key Toxicophores Identified by the Neural Network
{toxicophore_summary}

## Critical Atoms (by GNN Attention)
{critical_atoms_summary}

## Task
Provide a 2-3 sentence executive summary explaining:
1. The overall toxicity risk level
2. The primary structural features driving the prediction
3. The most likely biological mechanism

Be scientifically accurate and cite specific structural features. Do not speculate beyond the evidence provided."""

    # ═══════════════════════════════════════════════════════════════════════
    # Detailed Mechanism Prompt
    # ═══════════════════════════════════════════════════════════════════════
    DETAILED_MECHANISM = """You are an expert in molecular toxicology and drug metabolism. Provide a detailed mechanistic explanation for the predicted toxicity.

## Molecule
SMILES: {smiles}

## Neural Network Analysis
The Graph Neural Network identified the following structural features as important for toxicity prediction (listed by importance):

{toxicophore_details}

## Endpoint Predictions
{endpoint_predictions}

## Task
Provide a detailed scientific explanation covering:

1. **Metabolic Activation**: How could this molecule be metabolized to reactive intermediates?

2. **Molecular Targets**: What biological macromolecules (DNA, proteins, lipids) could be affected?

3. **Mechanism of Toxicity**: Describe the step-by-step mechanism by which the identified toxicophores could cause cellular damage.

4. **Structure-Activity Relationships**: How do the specific structural features contribute to the toxicity?

Be specific about chemical reactions, enzyme systems (e.g., CYP450 isoforms), and cellular pathways. Use proper chemical nomenclature."""

    # ═══════════════════════════════════════════════════════════════════════
    # Similar Compounds Prompt
    # ═══════════════════════════════════════════════════════════════════════
    SIMILAR_COMPOUNDS = """Based on the following molecular structure and identified toxic features, identify 3-5 well-documented toxic compounds with similar structural motifs.

## Query Molecule
SMILES: {smiles}

## Identified Toxic Features
{toxicophore_list}

## Task
List 3-5 known toxic compounds that share similar structural features. For each compound provide:
- Common name and SMILES (if known)
- The shared toxic motif
- Known toxicity type (e.g., hepatotoxic, mutagenic, carcinogenic)
- Brief note on documented toxicity

Focus on well-characterized compounds from toxicology literature. Prioritize compounds with similar mechanisms of toxicity."""

    # ═══════════════════════════════════════════════════════════════════════
    # Safety Recommendations Prompt  
    # ═══════════════════════════════════════════════════════════════════════
    SAFETY_RECOMMENDATIONS = """As a pharmaceutical safety scientist, provide actionable recommendations based on the toxicity prediction.

## Molecule Analysis
- SMILES: {smiles}
- Predicted Toxicity: {toxicity_probability:.1%}
- Primary Toxicophores: {toxicophore_names}
- Risk Level: {risk_level}

## Task
Provide 3-5 specific, actionable safety recommendations. Consider:

1. **Structural Modifications**: What changes could reduce toxicity while maintaining activity?
2. **Experimental Validation**: What assays should be prioritized?
3. **Risk Mitigation**: What precautions are needed if this compound advances?
4. **Regulatory Considerations**: What data would regulators require?

Be practical and specific. Recommendations should be immediately actionable by a medicinal chemistry team."""


class LLMProvider(ABC):
    """Abstract base class for LLM providers."""
    
    @abstractmethod
    def generate(self, prompt: str, max_tokens: int = 1000, temperature: float = 0.3) -> str:
        """Generate text completion from prompt."""
        pass
    
    @abstractmethod
    def is_available(self) -> bool:
        """Check if the LLM provider is available."""
        pass


class GroqLLMProvider(LLMProvider):
    """
    Groq LLM provider for high-speed inference.
    Uses LLaMA 3.3 70B for scientific reasoning.
    """

    is_mock = False
    MODEL_ID = "llama-3.3-70b-versatile"
    
    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or os.getenv('GROQ_API_KEY')
        self._client = None
        self._initialize_client()
    
    def _initialize_client(self):
        """Initialize the Groq client."""
        if not self.api_key:
            logger.warning("GROQ_API_KEY not found. LLM reasoning will be disabled.")
            return
        
        try:
            from groq import Groq
            self._client = Groq(api_key=self.api_key)
            logger.info(f"Groq client initialized with model: {self.MODEL_ID}")
        except ImportError:
            logger.error("groq package not installed. Run: pip install groq")
        except Exception as e:
            logger.error(f"Failed to initialize Groq client: {e}")
    
    def is_available(self) -> bool:
        return self._client is not None
    
    def generate(
        self, 
        prompt: str, 
        max_tokens: int = 1500,
        temperature: float = 0.3,
        system_prompt: Optional[str] = None
    ) -> str:
        """
        Generate completion using Groq LLaMA 3.3.
        
        Args:
            prompt: User prompt
            max_tokens: Maximum tokens in response
            temperature: Sampling temperature (lower = more deterministic)
            system_prompt: Optional system prompt
            
        Returns:
            Generated text response
        """
        if not self.is_available():
            return "[LLM reasoning unavailable - API key not configured]"
        
        try:
            messages = []
            
            if system_prompt:
                messages.append({
                    "role": "system",
                    "content": system_prompt
                })
            
            messages.append({
                "role": "user", 
                "content": prompt
            })
            
            response = self._client.chat.completions.create(
                model=self.MODEL_ID,
                messages=messages,
                temperature=temperature,
                max_tokens=max_tokens,
                top_p=0.9
            )
            
            return response.choices[0].message.content.strip()
            
        except Exception as e:
            logger.error(f"Groq API error: {e}")
            return f"[LLM reasoning failed: {str(e)}]"


class MockLLMProvider(LLMProvider):
    """
    Mock LLM provider for testing without API access.
    Returns template-based responses for development.

    WARNING: This provider fabricates responses. Any faithfulness/baseline number
    produced with it is NOT a scientific result and must never appear in the paper.
    Evaluation scripts refuse to use it unless --allow-mock is passed explicitly.
    """

    is_mock = True

    def is_available(self) -> bool:
        return True
    
    def generate(self, prompt: str, max_tokens: int = 1000, temperature: float = 0.3) -> str:
        """Return mock response for testing."""
        import re
        import json
        
        if "JSON" in prompt:
            # Let's check if this is the constrained prompt
            is_constrained = "High-Attention Substructures" in prompt
            
            if is_constrained:
                # Try to find high attention substructures in the evidence section only (after "High-Attention Substructures")
                evidence_idx = prompt.find("High-Attention Substructures")
                evidence_text = prompt[evidence_idx:] if evidence_idx != -1 else ""
                sub_matches = re.findall(r'\d+\.\s+([\w\s_-]+?)(?:\s*\(atoms\s*(\[[^\]]*\])\))?\n', evidence_text)
                if sub_matches:
                    first_sub = sub_matches[0]
                    primary_name = first_sub[0].strip()
                    primary_atoms = [6, 7, 8]
                    if first_sub[1]:
                        try:
                            primary_atoms = json.loads(first_sub[1])
                        except:
                            pass
                    
                    # Extract attention score if available
                    primary_attention = 0.85
                    attn_match = re.search(fr'{re.escape(first_sub[0])}.*?Attention:\s*([\d\.]+)%', prompt, re.DOTALL)
                    if attn_match:
                        primary_attention = float(attn_match.group(1)) / 100.0
                    
                    primary_mechanism = "Enzymatic reduction forms reactive intermediates."
                    # Look up mechanism from TOXICOPHORES if available
                    try:
                        try:
                            from utils.substructure_mapper import TOXICOPHORES
                        except ImportError:
                            from substructure_mapper import TOXICOPHORES
                        if primary_name in TOXICOPHORES:
                            primary_mechanism = TOXICOPHORES[primary_name]['mechanism']
                    except:
                        pass
                    
                    res = {
                        "executive_summary": f"The prediction is driven by the presence of a {primary_name} group.",
                        "primary_toxicophore": {
                            "name": primary_name,
                            "atoms": primary_atoms,
                            "attention_score": primary_attention,
                            "mechanism": primary_mechanism
                        },
                        "secondary_features": [],
                        "overall_mechanism": primary_mechanism,
                        "confidence": 0.95
                    }
                else:
                    # No high-attention substructures. Return no claims.
                    res = {
                        "executive_summary": "No active toxicophores were identified above the attention threshold.",
                        "primary_toxicophore": None,
                        "secondary_features": [],
                        "overall_mechanism": "The model prediction is based on global feature interactions rather than a single dominant toxicophore.",
                        "confidence": 0.95
                    }
            else:
                # Unconstrained mode: find a real toxicophore in the database based on SMILES
                primary_name = "Nitro"
                primary_atoms = [6, 7, 8]
                primary_attention = 0.85
                primary_mechanism = "Enzymatic reduction forms reactive nitroso intermediates."
                
                smiles_match = re.search(r'Molecule(?:\s*\(SMILES\))?:\s*([^\n\s]+)', prompt)
                if smiles_match:
                    smiles = smiles_match.group(1)
                    try:
                        from rdkit import Chem
                        try:
                            from utils.substructure_mapper import TOXICOPHORES
                        except ImportError:
                            from substructure_mapper import TOXICOPHORES
                        
                        mol = Chem.MolFromSmiles(smiles)
                        if mol:
                            mol = Chem.AddHs(mol)
                            for k, v in TOXICOPHORES.items():
                                patt = Chem.MolFromSmarts(v['smarts'])
                                if patt and mol.HasSubstructMatch(patt):
                                    primary_name = k
                                    primary_atoms = list(mol.GetSubstructMatch(patt))
                                    primary_attention = 0.8
                                    primary_mechanism = v['mechanism']
                                    break
                    except:
                        pass
                
                res = {
                    "executive_summary": f"The prediction is driven by the presence of a {primary_name} group.",
                    "primary_toxicophore": {
                        "name": primary_name,
                        "atoms": primary_atoms,
                        "attention_score": primary_attention,
                        "mechanism": primary_mechanism
                    },
                    "secondary_features": [],
                    "overall_mechanism": primary_mechanism,
                    "confidence": 0.95
                }
            
            return json.dumps(res)

        if "executive summary" in prompt.lower():
            return ("This molecule shows moderate toxicity risk due to the presence of "
                   "reactive functional groups identified by the neural network. "
                   "The primary concern is potential metabolic activation leading to "
                   "reactive intermediate formation.")
        elif "mechanism" in prompt.lower():
            return ("The identified toxicophores suggest a mechanism involving metabolic "
                   "activation by cytochrome P450 enzymes (primarily CYP3A4 and CYP2E1). "
                   "The reactive intermediates formed can covalently bind to cellular "
                   "proteins and nucleic acids, leading to cellular dysfunction and "
                   "potential genotoxicity.")
        elif "similar compounds" in prompt.lower():
            return ("1. **Aflatoxin B1** - Similar epoxide-forming potential\n"
                   "2. **Acetaminophen** - Shares reactive metabolite pathway\n"
                   "3. **Carbon tetrachloride** - Halogenated compound toxicity")
        else:
            return "[Mock LLM response for testing]"


class OpenAILLMProvider(LLMProvider):
    """
    OpenAI provider (GPT-4 family) for scientific reasoning.
    Uses the OpenAI Python SDK (>=1.0). Reads OPENAI_API_KEY.
    """

    is_mock = False
    MODEL_ID = os.getenv('OPENAI_MODEL', 'gpt-4o')

    def __init__(self, api_key: Optional[str] = None, model: Optional[str] = None,
                 base_url: Optional[str] = None):
        # OPENAI_BASE_URL lets this same provider target any OpenAI-compatible
        # gateway (e.g. OpenRouter: https://openrouter.ai/api/v1). Set OPENAI_MODEL
        # to that gateway's model id, e.g. meta-llama/llama-3.3-70b-instruct.
        self.api_key = api_key or os.getenv('OPENAI_API_KEY') or os.getenv('OPENROUTER_API_KEY')
        self.MODEL_ID = model or self.MODEL_ID
        self.base_url = base_url or os.getenv('OPENAI_BASE_URL')
        self._client = None
        if not self.api_key:
            logger.warning("OPENAI_API_KEY not found. OpenAI provider disabled.")
            return
        try:
            from openai import OpenAI
            kwargs = {'api_key': self.api_key}
            if self.base_url:
                kwargs['base_url'] = self.base_url
            self._client = OpenAI(**kwargs)
            logger.info(f"OpenAI-compatible client initialized: model={self.MODEL_ID} "
                        f"base_url={self.base_url or 'default'}")
        except ImportError:
            logger.error("openai package not installed. Run: pip install openai")
        except Exception as e:
            logger.error(f"Failed to initialize OpenAI client: {e}")

    def is_available(self) -> bool:
        return self._client is not None

    def generate(self, prompt: str, max_tokens: int = 1500,
                 temperature: float = 0.3, system_prompt: Optional[str] = None) -> str:
        if not self.is_available():
            return "[LLM reasoning unavailable - OpenAI key not configured]"
        try:
            messages = []
            if system_prompt:
                messages.append({"role": "system", "content": system_prompt})
            messages.append({"role": "user", "content": prompt})
            resp = self._client.chat.completions.create(
                model=self.MODEL_ID, messages=messages,
                temperature=temperature, max_tokens=max_tokens, top_p=0.9,
            )
            return resp.choices[0].message.content.strip()
        except Exception as e:
            logger.error(f"OpenAI API error: {e}")
            return f"[LLM reasoning failed: {str(e)}]"


# ═══════════════════════════════════════════════════════════════════════════
# Provider factory + integrity guard
# ═══════════════════════════════════════════════════════════════════════════

def get_llm_provider(preference: Optional[str] = None, allow_mock: bool = False) -> LLMProvider:
    """Return a real LLM provider, or raise rather than silently falling back to mock.

    Selection order (unless ``preference`` forces one):
      1. env LLM_PROVIDER in {groq, openai, mock}
      2. Groq if GROQ_API_KEY is set
      3. OpenAI if OPENAI_API_KEY is set

    A mock is returned ONLY when explicitly requested (preference/env == 'mock')
    AND allow_mock is True. This makes it impossible to produce mock-generated
    "results" by accident -- the root cause of the earlier invalid numbers.

    Set the model via GROQ (fixed) or OPENAI_MODEL env var.
    """
    pref = (preference or os.getenv('LLM_PROVIDER', 'auto')).lower()

    def _mock():
        if not allow_mock:
            raise RuntimeError(
                "Refusing to use MockLLMProvider for a real run. A mock fabricates "
                "responses; its numbers are not scientific results. Set GROQ_API_KEY "
                "or OPENAI_API_KEY, or pass allow_mock=True (test/dev only)."
            )
        logger.warning("Using MockLLMProvider (allow_mock=True) -- NOT for paper results.")
        return MockLLMProvider()

    if pref == 'mock':
        return _mock()
    if pref == 'groq':
        p = GroqLLMProvider()
        if p.is_available():
            return p
        raise RuntimeError("LLM_PROVIDER=groq but GROQ_API_KEY missing/invalid.")
    if pref == 'openai':
        p = OpenAILLMProvider()
        if p.is_available():
            return p
        raise RuntimeError("LLM_PROVIDER=openai but OPENAI_API_KEY missing/invalid.")

    # auto: try Groq, then OpenAI, else fail loudly
    groq = GroqLLMProvider()
    if groq.is_available():
        return groq
    openai_p = OpenAILLMProvider()
    if openai_p.is_available():
        return openai_p
    return _mock()


def assert_real_llm(llm: LLMProvider) -> LLMProvider:
    """Raise if ``llm`` is a mock. Call this at the top of any evaluation that
    writes numbers intended for the paper."""
    if getattr(llm, 'is_mock', False):
        raise RuntimeError(
            "A MockLLMProvider is in use. Refusing to produce paper numbers from "
            "fabricated LLM output. Configure GROQ_API_KEY or OPENAI_API_KEY."
        )
    return llm


class NeuroSymbolicReasoner:
    """
    Main reasoning engine combining GNN attention with LLM interpretation.
    
    This class orchestrates the complete explanation pipeline:
    1. Process GNN attention weights
    2. Map attention to chemical substructures
    3. Generate structured evidence
    4. Query LLM for scientific explanations
    5. Compile comprehensive report
    
    Usage:
        reasoner = NeuroSymbolicReasoner()
        report = reasoner.explain(
            smiles="c1ccc([N+](=O)[O-])cc1",
            attention_weights=attention_array,
            prediction_result=prediction
        )
    """
    
    # Tox21 endpoint names for reference
    TOX21_ENDPOINTS = [
        "NR-AR", "NR-AR-LBD", "NR-AhR", "NR-Aromatase", 
        "NR-ER", "NR-ER-LBD", "NR-PPAR-gamma",
        "SR-ARE", "SR-ATAD5", "SR-HSE", "SR-MMP", "SR-p53"
    ]
    
    def __init__(
        self, 
        llm_provider: Optional[LLMProvider] = None,
        use_mock: bool = False
    ):
        """
        Initialize the reasoner.
        
        Args:
            llm_provider: LLM provider instance (default: Groq)
            use_mock: If True, use mock LLM for testing
        """
        if use_mock:
            self.llm = MockLLMProvider()
            logger.info("Using Mock LLM provider for testing")
        elif llm_provider:
            self.llm = llm_provider
        else:
            self.llm = GroqLLMProvider()
        
        # Import substructure mapper
        try:
            from utils.substructure_mapper import SubstructureMapper
            self.substructure_mapper = SubstructureMapper()
            logger.info("Substructure mapper initialized")
        except ImportError:
            try:
                from substructure_mapper import SubstructureMapper
                self.substructure_mapper = SubstructureMapper()
            except ImportError:
                logger.warning("SubstructureMapper not available")
                self.substructure_mapper = None
        
        # RDKit for molecular properties
        try:
            from rdkit import Chem
            from rdkit.Chem import Descriptors, AllChem
            self.rdkit_available = True
        except ImportError:
            self.rdkit_available = False
            logger.warning("RDKit not available - molecular context limited")
    
    def _compute_molecular_context(self, smiles: str) -> MolecularContext:
        """Compute molecular properties for context."""
        context = MolecularContext(smiles=smiles)
        
        if not self.rdkit_available:
            return context
        
        from rdkit import Chem
        from rdkit.Chem import Descriptors, AllChem, rdMolDescriptors
        
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return context
        
        context.canonical_smiles = Chem.MolToSmiles(mol)
        context.molecular_formula = rdMolDescriptors.CalcMolFormula(mol)
        context.molecular_weight = Descriptors.MolWt(mol)
        context.num_atoms = mol.GetNumAtoms()
        context.num_heavy_atoms = Descriptors.HeavyAtomCount(mol)
        context.num_rings = rdMolDescriptors.CalcNumRings(mol)
        context.num_aromatic_rings = rdMolDescriptors.CalcNumAromaticRings(mol)
        context.logp = Descriptors.MolLogP(mol)
        context.tpsa = Descriptors.TPSA(mol)
        
        return context
    
    def _classify_risk_level(self, toxicity_prob: float) -> RiskLevel:
        """Classify risk level based on toxicity probability."""
        if toxicity_prob >= 0.9:
            return RiskLevel.CRITICAL
        elif toxicity_prob >= 0.7:
            return RiskLevel.HIGH
        elif toxicity_prob >= 0.4:
            return RiskLevel.MODERATE
        elif toxicity_prob >= 0.2:
            return RiskLevel.LOW
        else:
            return RiskLevel.MINIMAL
    
    def _extract_evidence(
        self,
        smiles: str,
        attention_weights: Any,
        threshold: float = 0.08
    ) -> Tuple[List[ToxicityEvidence], List[Dict]]:
        """
        Extract toxicity evidence from attention weights.
        
        Returns:
            Tuple of (toxicophore_evidence, critical_atoms)
        """
        import numpy as np
        attention_weights = np.array(attention_weights)
        
        toxicophores = []
        critical_atoms = []
        
        if self.substructure_mapper:
            # Get substructure matches
            matches = self.substructure_mapper.identify_substructures(
                smiles, attention_weights, threshold=threshold
            )
            
            for match in matches[:5]:  # Top 5
                evidence = ToxicityEvidence(
                    substructure_name=match.name.replace('_', ' ').title(),
                    smarts_pattern=match.smarts,
                    atom_indices=match.atoms,
                    attention_score=match.avg_attention,
                    toxicity_category=match.toxicity_category,
                    mechanism=match.mechanism,
                    confidence=min(1.0, match.avg_attention * 3)
                )
                toxicophores.append(evidence)
            
            # Get critical atoms
            atom_info = self.substructure_mapper.get_top_atoms(
                smiles, attention_weights, top_k=5
            )
            critical_atoms = atom_info
        
        return toxicophores, critical_atoms
    
    def _format_toxicophore_summary(self, evidence: List[ToxicityEvidence]) -> str:
        """Format toxicophores for prompt injection."""
        if not evidence:
            return "No known toxicophores identified with high confidence."
        
        lines = []
        for i, e in enumerate(evidence, 1):
            lines.append(
                f"{i}. **{e.substructure_name}** (atoms {e.atom_indices})\n"
                f"   - Attention Score: {e.attention_score:.1%}\n"
                f"   - Category: {e.toxicity_category}\n"
                f"   - Mechanism: {e.mechanism[:100]}..."
            )
        return "\n".join(lines)
    
    def _format_critical_atoms(self, atoms: List[Dict]) -> str:
        """Format critical atoms for prompt injection."""
        if not atoms:
            return "No critical atoms identified."
        
        lines = []
        for a in atoms:
            lines.append(
                f"- Atom {a['index']} ({a['symbol']}): "
                f"Attention {a['attention']:.1%}, "
                f"Aromatic: {a['is_aromatic']}, "
                f"Neighbors: {', '.join(a['neighbors'])}"
            )
        return "\n".join(lines)
    
    def _format_endpoint_predictions(
        self, 
        prediction: PredictionResult
    ) -> str:
        """Format endpoint predictions for prompt."""
        if not prediction.endpoint_scores:
            return f"Overall Toxicity: {prediction.overall_toxicity:.1%}"
        
        lines = [f"Overall Toxicity: {prediction.overall_toxicity:.1%}\n"]
        lines.append("Individual Endpoints:")
        
        # Sort by score
        sorted_endpoints = sorted(
            prediction.endpoint_scores.items(),
            key=lambda x: x[1],
            reverse=True
        )
        
        for name, score in sorted_endpoints:
            status = "⚠️ TOXIC" if score > 0.5 else "✓ Safe"
            lines.append(f"  - {name}: {score:.1%} {status}")
        
        return "\n".join(lines)
    
    def explain(
        self,
        smiles: str,
        attention_weights: Any,
        prediction_result: Optional[PredictionResult] = None,
        overall_toxicity: Optional[float] = None,
        endpoint_scores: Optional[Dict[str, float]] = None,
        generate_all_sections: bool = True
    ) -> ExplanationReport:
        """
        Generate a comprehensive explanation report.
        
        Args:
            smiles: SMILES string of the molecule
            attention_weights: Per-atom attention scores from GNN
            prediction_result: Structured prediction result (optional)
            overall_toxicity: Overall toxicity probability (if no PredictionResult)
            endpoint_scores: Individual endpoint scores (if no PredictionResult)
            generate_all_sections: If True, generate all explanation sections
            
        Returns:
            ExplanationReport with complete analysis
        """
        import numpy as np
        
        logger.info(f"Generating explanation for: {smiles[:50]}...")
        
        # Initialize report
        report = ExplanationReport(
            timestamp=datetime.now().isoformat(),
            smiles=smiles
        )
        
        # Compute molecular context
        report.molecular_context = self._compute_molecular_context(smiles)
        
        # Build prediction result if not provided
        if prediction_result is None:
            tox_prob = overall_toxicity or 0.5
            prediction_result = PredictionResult(
                overall_toxicity=tox_prob,
                endpoint_scores=endpoint_scores or {},
                risk_level=self._classify_risk_level(tox_prob)
            )
        
        report.prediction = prediction_result
        
        # Extract toxicity evidence from attention
        attention_weights = np.array(attention_weights)
        toxicophores, critical_atoms = self._extract_evidence(
            smiles, attention_weights
        )
        
        report.identified_toxicophores = toxicophores
        report.critical_atoms = critical_atoms
        
        # Calculate attention coverage (how much we can explain)
        explained_attention = sum(t.attention_score for t in toxicophores)
        report.attention_coverage = min(1.0, explained_attention)
        
        if not generate_all_sections:
            return report
        
        # ═══════════════════════════════════════════════════════════════════
        # Generate LLM Explanations
        # ═══════════════════════════════════════════════════════════════════
        
        # 1. Executive Summary
        summary_prompt = PromptTemplate.EXECUTIVE_SUMMARY.format(
            smiles=smiles,
            molecular_weight=report.molecular_context.molecular_weight,
            toxicity_probability=prediction_result.overall_toxicity,
            risk_level=prediction_result.risk_level.value,
            toxicophore_summary=self._format_toxicophore_summary(toxicophores),
            critical_atoms_summary=self._format_critical_atoms(critical_atoms)
        )
        
        report.executive_summary = self.llm.generate(
            summary_prompt,
            max_tokens=300,
            temperature=0.2
        )
        
        # 2. Detailed Mechanism
        mechanism_prompt = PromptTemplate.DETAILED_MECHANISM.format(
            smiles=smiles,
            toxicophore_details=self._format_toxicophore_summary(toxicophores),
            endpoint_predictions=self._format_endpoint_predictions(prediction_result)
        )
        
        report.detailed_mechanism = self.llm.generate(
            mechanism_prompt,
            max_tokens=800,
            temperature=0.3
        )
        
        # 3. Similar Compounds
        if toxicophores:
            toxicophore_list = "\n".join([
                f"- {t.substructure_name}: {t.mechanism[:80]}..."
                for t in toxicophores[:3]
            ])
            
            similar_prompt = PromptTemplate.SIMILAR_COMPOUNDS.format(
                smiles=smiles,
                toxicophore_list=toxicophore_list
            )
            
            similar_response = self.llm.generate(
                similar_prompt,
                max_tokens=500,
                temperature=0.3
            )
            
            # Parse similar compounds (simple extraction)
            report.similar_compounds = [
                line.strip() for line in similar_response.split('\n')
                if line.strip() and (line.strip()[0].isdigit() or line.strip().startswith('-'))
            ][:5]
        
        # 4. Safety Recommendations
        toxicophore_names = ", ".join([t.substructure_name for t in toxicophores[:3]]) or "None identified"
        
        safety_prompt = PromptTemplate.SAFETY_RECOMMENDATIONS.format(
            smiles=smiles,
            toxicity_probability=prediction_result.overall_toxicity,
            toxicophore_names=toxicophore_names,
            risk_level=prediction_result.risk_level.value
        )
        
        safety_response = self.llm.generate(
            safety_prompt,
            max_tokens=600,
            temperature=0.3
        )
        
        # Parse recommendations
        report.safety_recommendations = [
            line.strip() for line in safety_response.split('\n')
            if line.strip() and (line.strip()[0].isdigit() or line.strip().startswith('-'))
        ][:5]
        
        # Calculate overall confidence
        report.explanation_confidence = self._calculate_confidence(
            toxicophores, critical_atoms, prediction_result
        )
        
        logger.info(f"Explanation complete. Confidence: {report.explanation_confidence:.1%}")
        
        return report
    
    def _calculate_confidence(
        self,
        toxicophores: List[ToxicityEvidence],
        critical_atoms: List[Dict],
        prediction: PredictionResult
    ) -> float:
        """
        Calculate overall explanation confidence.
        Higher confidence when:
        - More known toxicophores identified
        - Higher attention on identified features
        - Clearer prediction (not near 0.5)
        """
        # Factor 1: Toxicophore coverage
        toxicophore_score = min(1.0, len(toxicophores) / 3)
        
        # Factor 2: Attention concentration
        if toxicophores:
            attention_score = sum(t.attention_score for t in toxicophores)
            attention_score = min(1.0, attention_score)
        else:
            attention_score = 0.3
        
        # Factor 3: Prediction clarity
        pred_clarity = abs(prediction.overall_toxicity - 0.5) * 2
        
        # Weighted average
        confidence = (
            0.4 * toxicophore_score +
            0.3 * attention_score +
            0.3 * pred_clarity
        )
        
        return min(1.0, max(0.0, confidence))
    
    def explain_batch(
        self,
        molecules: List[Dict],
        progress_callback: Optional[callable] = None
    ) -> List[ExplanationReport]:
        """
        Generate explanations for multiple molecules.
        
        Args:
            molecules: List of dicts with 'smiles', 'attention', 'prediction'
            progress_callback: Optional callback(i, total) for progress updates
            
        Returns:
            List of ExplanationReport objects
        """
        reports = []
        total = len(molecules)
        
        for i, mol_data in enumerate(molecules):
            if progress_callback:
                progress_callback(i, total)
            
            report = self.explain(
                smiles=mol_data['smiles'],
                attention_weights=mol_data['attention'],
                overall_toxicity=mol_data.get('prediction'),
                endpoint_scores=mol_data.get('endpoint_scores')
            )
            reports.append(report)
        
        return reports


# ═══════════════════════════════════════════════════════════════════════════
# Factory Functions
# ═══════════════════════════════════════════════════════════════════════════

def create_reasoner(
    use_groq: bool = True,
    api_key: Optional[str] = None,
    use_mock: bool = False
) -> NeuroSymbolicReasoner:
    """
    Factory function to create a configured reasoner.
    
    Args:
        use_groq: If True, use Groq LLM (default)
        api_key: Optional API key override
        use_mock: If True, use mock LLM for testing
        
    Returns:
        Configured NeuroSymbolicReasoner instance
    """
    if use_mock:
        return NeuroSymbolicReasoner(use_mock=True)
    elif use_groq:
        provider = GroqLLMProvider(api_key=api_key)
        return NeuroSymbolicReasoner(llm_provider=provider)
    else:
        return NeuroSymbolicReasoner(use_mock=True)


# ═══════════════════════════════════════════════════════════════════════════
# Test Code
# ═══════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    import numpy as np
    
    print("Testing Neuro-Symbolic Reasoner...")
    print("=" * 60)
    
    # Create reasoner with mock LLM for testing
    reasoner = create_reasoner(use_mock=True)
    
    # Test molecule: Nitrobenzene
    smiles = "c1ccc([N+](=O)[O-])cc1"
    
    # Simulate attention weights (higher for nitro group)
    n_atoms = 9  # Nitrobenzene has 9 heavy atoms
    attention = np.random.uniform(0.05, 0.12, n_atoms)
    attention[6:9] = np.array([0.25, 0.20, 0.15])  # Nitro group
    attention = attention / attention.sum()
    
    print(f"Test molecule: Nitrobenzene ({smiles})")
    print(f"Attention weights: {attention}")
    
    # Create prediction
    prediction = PredictionResult(
        overall_toxicity=0.82,
        endpoint_scores={
            'NR-AhR': 0.91,
            'SR-p53': 0.78,
            'SR-MMP': 0.65,
            'NR-AR': 0.12
        },
        risk_level=RiskLevel.HIGH
    )
    
    # Generate explanation
    print("\nGenerating explanation...")
    report = reasoner.explain(
        smiles=smiles,
        attention_weights=attention,
        prediction_result=prediction
    )
    
    print("\n" + "=" * 60)
    print("EXPLANATION REPORT")
    print("=" * 60)
    print(f"\nMolecule: {report.smiles}")
    print(f"Risk Level: {report.prediction.risk_level.value}")
    print(f"Toxicity: {report.prediction.overall_toxicity:.1%}")
    print(f"Explanation Confidence: {report.explanation_confidence:.1%}")
    
    print(f"\nIdentified Toxicophores: {len(report.identified_toxicophores)}")
    for t in report.identified_toxicophores:
        print(f"  - {t.substructure_name}: {t.attention_score:.1%} ({t.toxicity_category})")
    
    print(f"\nExecutive Summary:\n{report.executive_summary}")
    
    print("\n✅ Neuro-Symbolic Reasoner ready!")
    
    # Test JSON export
    print("\n" + "=" * 60)
    print("JSON Export Test:")
    print(report.to_json()[:500] + "...")
